create table public.students (
  id uuid primary key default gen_random_uuid(),
  student_code text unique,                            -- auto-generated by trigger, e.g. CLY-2026-0001
  user_id uuid unique references auth.users(id) on delete set null,
  name text not null,
  email text not null unique,
  phone text,
  course text not null,
  batch text not null,
  joining_date date not null default current_date,
  original_fee numeric(12,2) not null check (original_fee >= 0),
  scholarship numeric(12,2) not null default 0 check (scholarship >= 0),
  final_fee numeric(12,2) generated always as (original_fee - scholarship) stored,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint scholarship_not_exceed_fee check (scholarship <= original_fee)
);

create index idx_students_batch on public.students(batch);
create index idx_students_course on public.students(course);
create index idx_students_email on public.students(email);
create index idx_students_user_id on public.students(user_id);

create trigger set_students_updated_at
  before update on public.students
  for each row execute function public.set_updated_at();
